# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: frontend

# The type key specifies the language and version for your application.
type: 'nodejs:14'

disk: 256

# The hooks that will be triggered when the package is deployed.
hooks:
  build: |
    npm ci
    npm run build

# The configuration of the application when it is exposed to the web.
web:
  commands:
    start: NODE_ICU_DATA=$(node-full-icu-path) npx next start -p $PORT
