# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

# @TODO: hardcoded domains are necessary due to multisite behaviour, can be deleted when upgrading P.sh.
'https://cms.eurofiber.com.{default}/':
  type: upstream
  upstream: 'drupal:http'
  cache:
    enabled: true
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

'http://cms.eurofiber.com.{default}/':
  type: redirect
  to: 'https://cms.eurofiber.com.{default}/'

'https://www.{default}/':
  type: upstream
  upstream: 'frontend:http'

'http://www.{default}/':
  type: redirect
  to: 'https://www.{default}/'
